project: 
  type: website

website:
  title: "Your_Name - Mechanical Engineering Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Your_Name 2024©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Personal Projects"
        file: projects.qmd
      - text: "Capstone"
        file: capstone.qmd
      - text: "Mechatronics"
        file: mechatronics.qmd
      - text: "Coding Projects"
        file: coding.qmd
      - text: "Internship"
        file: internship.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Personal Projects"
      style: "docked"
      background: light
      contents:
        - text: "Personal Projects"
          file: projects.qmd
        - text: "---"
        - text: "Project 1"
          file: Personal_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Personal_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Personal_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Personal_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Personal_Projects/project5.qmd
        - text: "---"
    - title: "Capstone"
      style: "docked"
      background: light
      contents:
        - text: "Capstone"
          file: capstone.qmd
        - text: "---"
        - text: "Project 1"
          file: Capstone_Project/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Capstone_Project/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Capstone_Project/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Capstone_Project/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Capstone_Project/project5.qmd
        - text: "---"
    - title: "Mechatronics"
      style: "docked"
      background: light
      contents:
        - text: "Mechatronics"
          file: mechatronics.qmd
        - text: "---"
        - text: "Project 1"
          file: Mechatronics/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Mechatronics/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Mechatronics/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Mechatronics/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Mechatronics/project5.qmd
        - text: "---"
    - title: "Coding Projects"
      style: "docked"
      background: light
      contents:
        - text: "Coding Projects"
          file: coding.qmd
        - text: "---"
        - text: "Project 1"
          file: Coding_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Coding_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Coding_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Coding_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Coding_Projects/project5.qmd
        - text: "---"
    - title: "Internship"
      style: "docked"
      background: light
      contents:
        - text: "Internahip"
          file: internship.qmd
        - text: "---"
        - text: "Project 1"
          file: Internship/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Internship/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Internship/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Internship/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Internship/project5.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



